### ISSUE TITLE
Audio device not detected on Linux

### ISSUE THREAD

**Issue by dalum** [JuliaMultimedia/SimpleDirectMediaLayer.jl#51] opened 2020-08-07 23:43 UTC
Just noticed that after upgrading to v0.2.* (so, using the JLLs), audio no longer works on Linux (I haven't tested on other OSs).  The tests are passing fine, since the tests for audio contains a check `if device == 0` that skips the tests if the audio device isn't found.  I'm not entirely sure how to fix it, but since it works pre-JLL, I guess there is an issue with the provided binaries.

**Comment by dalum** [comment] 2020-08-08 19:35
I've spent some time debugging it.  It turns out that if I replace `libSDL2-2.0.so.0.12.0` in the artifact with my system `libSDL2-2.0.so.0.12.0`, then audio works fine again.  So there must be something wrong with the `.so` file in the JLL.

**Comment by aviks** [comment] 2020-08-08 22:46
I just wanted to report that I use the latest SDL jll on windows 10, and audio does play successfully.

**Comment by aviks** [comment] 2022-09-24 14:40
Duplicate of #52. Further discussion there.

**Closed** 2022-10-29 15:45 UTC
